//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DistanciasCliente.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DistanciasServerImplPortBinding", Namespace="http://server/")]
    public partial class DistanciasServerImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback calcularDistanciaMultiplasCidadesOperationCompleted;
        
        private System.Threading.SendOrPostCallback calcularDistanciaMaximaOperationCompleted;
        
        private System.Threading.SendOrPostCallback calcularDistanciaDuasCidadesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DistanciasServerImplService() {
            this.Url = global::DistanciasCliente.Properties.Settings.Default.DistanciasCliente_localhost_DistanciasServerImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event calcularDistanciaMultiplasCidadesCompletedEventHandler calcularDistanciaMultiplasCidadesCompleted;
        
        /// <remarks/>
        public event calcularDistanciaMaximaCompletedEventHandler calcularDistanciaMaximaCompleted;
        
        /// <remarks/>
        public event calcularDistanciaDuasCidadesCompletedEventHandler calcularDistanciaDuasCidadesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server/", ResponseNamespace="http://server/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string calcularDistanciaMultiplasCidades(string arg0, [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] arg1) {
            object[] results = this.Invoke("calcularDistanciaMultiplasCidades", new object[] {
                        arg0,
                        arg1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calcularDistanciaMultiplasCidadesAsync(string arg0, string[] arg1) {
            this.calcularDistanciaMultiplasCidadesAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void calcularDistanciaMultiplasCidadesAsync(string arg0, string[] arg1, object userState) {
            if ((this.calcularDistanciaMultiplasCidadesOperationCompleted == null)) {
                this.calcularDistanciaMultiplasCidadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalcularDistanciaMultiplasCidadesOperationCompleted);
            }
            this.InvokeAsync("calcularDistanciaMultiplasCidades", new object[] {
                        arg0,
                        arg1}, this.calcularDistanciaMultiplasCidadesOperationCompleted, userState);
        }
        
        private void OncalcularDistanciaMultiplasCidadesOperationCompleted(object arg) {
            if ((this.calcularDistanciaMultiplasCidadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calcularDistanciaMultiplasCidadesCompleted(this, new calcularDistanciaMultiplasCidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server/", ResponseNamespace="http://server/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] calcularDistanciaMaxima(string arg0, int arg1) {
            object[] results = this.Invoke("calcularDistanciaMaxima", new object[] {
                        arg0,
                        arg1});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void calcularDistanciaMaximaAsync(string arg0, int arg1) {
            this.calcularDistanciaMaximaAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void calcularDistanciaMaximaAsync(string arg0, int arg1, object userState) {
            if ((this.calcularDistanciaMaximaOperationCompleted == null)) {
                this.calcularDistanciaMaximaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalcularDistanciaMaximaOperationCompleted);
            }
            this.InvokeAsync("calcularDistanciaMaxima", new object[] {
                        arg0,
                        arg1}, this.calcularDistanciaMaximaOperationCompleted, userState);
        }
        
        private void OncalcularDistanciaMaximaOperationCompleted(object arg) {
            if ((this.calcularDistanciaMaximaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calcularDistanciaMaximaCompleted(this, new calcularDistanciaMaximaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://server/", ResponseNamespace="http://server/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string calcularDistanciaDuasCidades(string arg0, string arg1) {
            object[] results = this.Invoke("calcularDistanciaDuasCidades", new object[] {
                        arg0,
                        arg1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calcularDistanciaDuasCidadesAsync(string arg0, string arg1) {
            this.calcularDistanciaDuasCidadesAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void calcularDistanciaDuasCidadesAsync(string arg0, string arg1, object userState) {
            if ((this.calcularDistanciaDuasCidadesOperationCompleted == null)) {
                this.calcularDistanciaDuasCidadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalcularDistanciaDuasCidadesOperationCompleted);
            }
            this.InvokeAsync("calcularDistanciaDuasCidades", new object[] {
                        arg0,
                        arg1}, this.calcularDistanciaDuasCidadesOperationCompleted, userState);
        }
        
        private void OncalcularDistanciaDuasCidadesOperationCompleted(object arg) {
            if ((this.calcularDistanciaDuasCidadesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calcularDistanciaDuasCidadesCompleted(this, new calcularDistanciaDuasCidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void calcularDistanciaMultiplasCidadesCompletedEventHandler(object sender, calcularDistanciaMultiplasCidadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calcularDistanciaMultiplasCidadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calcularDistanciaMultiplasCidadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void calcularDistanciaMaximaCompletedEventHandler(object sender, calcularDistanciaMaximaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calcularDistanciaMaximaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calcularDistanciaMaximaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void calcularDistanciaDuasCidadesCompletedEventHandler(object sender, calcularDistanciaDuasCidadesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calcularDistanciaDuasCidadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calcularDistanciaDuasCidadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591